name: 'Setup Idris'
description: 'Install Idris compiler'
inputs:
  language-version: 
    description: 'Idris version'
    required: true
    default: 2
runs:
  using: 'docker'
  image: ${{ ['dgellow/idris', 'dgellow/idris2'][inputs.language-version - 1] }}
