name: 'Setup Idris'
description: 'Install Idris'
branding:
  color: red
  icon: cpu
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: sudo apt-get -y install chezscheme
      shell: bash
    - name: Get latest build
      id: idris2build
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: sergeyshpadyrev/setup-idris-builds
        excludes: prerelease, draft
    - name: Download idris2
      run: |
        wget -O idris2-ubuntu.tar.gz https://github.com/sergeyshpadyrev/setup-idris-builds/releases/download/${{ steps.idris2build.outputs.release }}/idris2-ubuntu.tar.gz 
        tar -xvf idris2-ubuntu.tar.gz -C $HOME
        rm ./idris2-ubuntu.tar.gz
      shell: bash
    - name: Put idris2 executable to path
      run: echo "$HOME/.idris2/bin/" >> $GITHUB_PATH
      shell: bash
    - name: Make alias for idris2
      run: ln -sf $HOME/.idris2/bin/idris2 $HOME/.idris2/bin/idris
      shell: bash
