name: 'Setup Idris'
description: 'Install Idris compiler'
inputs:
  idris-version: 
    description: 'Idris version'
    required: true
    default: 'idris2'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.idris-version }}
