name: 'Setup Idris'
description: 'Install Idris compiler'
inputs:
  idris-version: 
    description: 'Idris version'
    required: true
    default: 2
runs:
  using: 'docker'
  image: Dockerfile ${{ inputs.idris-version }}
