name: 'Setup Idris'
description: 'Install Idris'
inputs:
  idris-version:  
    description: 'Idris version (1 or 2)'
    required: true
    default: 2
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: sudo apt-get -y install build-essential clang chezscheme
      shell: bash
    - name: Checkout idris2 repository
      uses: actions/checkout@v3
      with:
        repository: idris-lang/Idris2
        path: idris2-source
        ref: v0.3.0
    - name: Build idris2
      run: |
        cd idris2-source
        export SCHEME=scheme
        export PATH="${PATH}:~/.idris2/bin"
        make bootstrap
        make install
      shell: bash
    - name: Put idris2 executable to path
      run: echo 'export PATH="~/.idris2/bin/:${PATH}"' >> "${HOME}/.bashrc"
      shell: bash
