name: 'Setup Idris'
description: 'Install Idris'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: sudo apt-get -y install build-essential clang chezscheme
      shell: bash
    - name: Checkout idris2 repository
      uses: actions/checkout@v3
      with:
        repository: idris-lang/Idris2
        path: idris2-source
        ref: v0.3.0
    - name: Build idris2
      run: |
        cd idris2-source
        export SCHEME=scheme
        export PATH="${PATH}:~/.idris2/bin"
        make bootstrap
        make install
      shell: bash
    - name: Test idris2
      run: ls ~/.idris2/bin/
      shell: bash
    - name: Test idris22
      run: ~/.idris2/bin/idris2 -v
      shell: bash
    - name: Put idris2 executable to path
      run: echo "$HOME/.idris2/bin/" >> $GITHUB_PATH
      shell: bash
