name: 'Setup Idris'
description: 'Install Idris'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: sudo apt-get -y install chezscheme
      shell: bash
    - name: Download idris2
      run: |
        wget -O idris2-ubuntu.tar.gz https://github.com/sergeyshpadyrev/setup-idris-builds/releases/download/latest/idris2-ubuntu.tar.gz 
        tar -xvf idris2-ubuntu.tar.gz -C $HOME
        rm ./idris2-ubuntu.tar.gz
      shell: bash
    - name: Put idris2 executable to path
      run: echo "$HOME/.idris2/bin/" >> $GITHUB_PATH
      shell: bash
