name: 'Setup Idris 2'
description: 'Install Idris 2'
env: 
  SCHEME: scheme
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: sudo apt-get -y install build-essential git clang chezscheme
      shell: bash
    - name: Checkout idris2 repository
      uses: actions/checkout@v3
      with:
        name: idris-lang/Idris2
        path: idris2-source
        ref: v0.3.0
    - name: Build idris2
      run: |
        cd idris2-source
        export PATH="${PATH}:/root/.idris2/bin"
        make bootstrap
        make install
      shell: bash
    - name: Put idris2 executable to path
      run: echo 'export PATH="/root/.idris2/bin/:${PATH}"' >> "${HOME}/.bashrc"
      shell: bash
